### ISSUE TITLE
NHibernate: System.Reflection.TargetException : Object does not match target type.

### ISSUE THREAD

**Issue by piolo108** [spring-projects/spring-net#97] opened 2015-02-05 20:32 UTC
After upgrading from 1.3.2 to 2.0 RC2 I am getting the following error: 

System.Reflection.TargetException : Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NHibernate.Proxy.DefaultLazyInitializer.Intercept(InvocationInfo info)

I need to look into it, but maybe related to a bug in NHibernate 4.0.0.4.  Is there a road map to integrate with NHibernate 4.0.3?

**Comment by sbohlen** [comment] 2015-02-05 20:51
We can certainly refresh our NH dependency before GA, but I likely can't get to this until the weekend.  In the interim, could you perhaps use a simple binding redirect to reference in the updated NH 4.0.3 binary and evaluate/confirm the source of the issue that way --?

**Comment by piolo108** [comment] 2015-02-05 23:18
Getting all the bug fixes in NH 4.x would awesome before GA.  Binding redirect worked for the following assemblies in case anyone else runs into this issue.

Since NHibernate.ByteCode.Castle 3.1.0.4000 still references NHibernate 3.1.0.4000. I tried to use NH built-in proxy support, but my unit tests were failing. Binding redirect worked to support NHibernate.ByteCode.Castle with NH 4

**Comment by sbohlen** [comment] 2015-02-05 23:52
Can you clarify that comment for me a bit further?  I think you are indicating that you redirected the `Spring.Data.NHibernate4` dependency to point to NHibernate 3.1.0.4000 (?)

I was actually suggesting that you redirect the `Spring.Data.NHibernate4` assembly to use NHibernate 4.0.3 as a test ... is that possible?

Either way, I'll update that dependency in MASTER this weekend, but at the same time I'm concerned that this issue may (somehow) have escaped our unit tests since no tests are presently failing with the present NH4 version dependency in RC2.  Because of this, if we update our dependency chain and our tests _still_ pass, I'm not 100% certain that this will actually be indicative that we've solved the issue/problem per se.

Could you (perhaps) either provide us a failing test case or else fork and pull MASTER once we've updated the dependency and build it locally so that you could test your code against the updated NH dependency after I've committed it...?

**Comment by piolo108** [comment] 2015-02-06 00:21
I apologize for the confusion:

My failing unit test was related to NHibernate using its internal proxy factory:

NHibernate.Bytecode.DefaultProxyFactoryFactory in NHibernate.dll (doesn't work, or causes my unit test to fail)
NHibernate.ByteCode.Castle.ProxyFactoryFactory in NHibernate.ByteCode.Castle.dll (works, but requires rebinding because NHibernate.ByteCode.Castle references NH 3.1.0

Below are my redirects:

  
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NHibernate" publicKeyToken="aa95f207798dfdb4" culture="neutral" />
        <bindingRedirect oldVersion="3.1.0.4000" newVersion="4.0.0.4000" />
      </dependentAssembly>
    </assemblyBinding>
    
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
        <bindingRedirect oldVersion="2.5.1.0" newVersion="3.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>

**Comment by sbohlen** [comment] 2015-02-06 00:37
Ok, got it, thanks.

So just to be 100% clear, you've confirmed that this isn't an issue with Spring.Net per se so we can close this issue now, correct --? (tho we will still update to the latest NH4 release before we cut a final 2.0.0 GA)

-Steve B.

-----Original Message-----

**Comment by piolo108** [comment] 2015-02-06 14:03
correct, this issue can be closed. Thank you!

**Closed** 2015-02-06 14:03 UTC
Labels: Bug
