### ISSUE TITLE
Spring.Template.Velocity depending on the outdated Apache NVelocity

### ISSUE THREAD

**Issue by djechelon** [spring-projects/spring-net#102] opened 2015-03-04 20:42 UTC
Since Castle Project forked their own version of NVelocity which is more maintained than the old dead NVelocity, and supposing their APIs are equal if not even exactly the same, I suggest one of the two options:
- Switching from NVelocity to Castle Velocity
- Forking a new Spring.Template.Velocity.Castle with support for Castle Velocity

I have not yet used Spring.net and Velocity but I'll be doing it soon.
What do you think about it? I think in the next weeks I could try one of the two options by myself on Spring code. Meanwhile I tried, out of curiosity, to fork Spring and switch from NVelocity to Castle: all tests passed

https://github.com/djechelon/spring-net/commit/f8068653dfbfa1a969d6bb239e1af22792ce275b

**Comment by sbohlen** [comment] 2015-03-04 21:54
I'd probably prefer option 2, creating a new `Spring.Template.Velocity.Castle` project with support for Castle Velocity and leaving the existing`Spring.Template.Velocity` project untouched.

My thinking is that this would both permit users to make a conscious choice re: which Velocity implementation they choose to adopt as well as be more 'honest' about the intent of the Spring Module they are selecting.

Over time, if use of the `Spring.Template.Velocity` module is worth removing from Spring.NET entirely in favor of _only_ the `Spring.Template.Velocity.Castle` project, then having them separate makes that an easier action to perform as well.

Once you have had a chance to experiment/explore this space more deeply, why don't you circle back here and offer your feedback/results so that we can discuss it further and come to agreement re: which way makes the most sense after you've completed more research...

Note that if we do decide to introduce a new `Spring.Template.Velocity.Castle` project, I'd probably want any pull-requests for this to be built by _linking_ to the same source files that are in the `Spring.Template.Velocity` project (where possible!) in the same manner as the existing multiple projects that support various NHibernate versions so that we don't end up with duplicate source code files everywhere, increasing the long-term maintenance burden if/when bugfixes are introduced into the project(s).

**Comment by djechelon** [comment] 2015-03-10 14:35
Could you illustrate how to create a new project with links to existing source files? I don't get it, sorry

**Comment by sbohlen** [comment] 2015-03-10 14:41
Sure; its not all that obvious how to do this, but this MSDN article section shows it in action: https://msdn.microsoft.com/en-us/library/windows/apps/jj714082(v=vs.105).aspx#BKMK_HowtolinkafileinyourappprojectusingAddasLink

Note that this article seems to be Windows/WindowsPhone app-centric, but the section on add-as-link is broadly relevant to all other project types as well.  This was the technique used in the `Spring.Data.NHibernateXYZ` projects so that the source files only exist "on disk" in `Spring.Data.NHibernate` but are then added-as-links into e.g., `Spring.Data.NHibernate32`, `Spring.Data.NHibernate4` where appropriate so as not to produce duplicate files in source-control.

Hope this helps!

**Comment by djechelon** [comment] 2015-03-10 16:07
Hi, how about namespaces? I'm starting the new project on my fork, but I wonder whether to keep `Spring.Template.Velocity` namespace (good for me) or adding a `.Castle` suffix (bad for me).

I support for the first, as it allows replacing old instances of Velocity with Castle. Also, using modified namespace will prevent sharing source files.

What do you think about it?

**Comment by sbohlen** [comment] 2015-03-10 16:22
I agree w all your points.  Same namespace is fine (at least for now).  

Similar to how Nhibernate was handled, there's (probably?) no use-case where you'd ever want/need both assemblies at the same time, and same namespace would facilitate substitution, as you point out.

-Steve B.

-----Original Message-----

**Comment by djechelon** [comment] 2015-03-10 17:04
Ok I have made a first commit

https://github.com/djechelon/spring-net/commit/4623d52a56d5d6290f4617d20c4049066d5bef52

Code compiles but test don't yet run because there could be some reference still left to old Spring.Template.Velocity (resulting in `TypeLoadException`).

More than the standard NUnit tests, I'll try to import the DLL into my project to get a feedback before requesting a pull. If you can provide me feedback on how to make the tests run I'll appreciate that.

**Comment by sbohlen** [comment] 2015-03-10 20:51
In the next day or so I'll try to fork your fork :) and see if I can identify why the tests are failing with the `TypeLoadException` in order to at least get them to the point where they are failing for e.g., logical reasons of incompatibilities vs. structural reasons as you seem to be suggesting is the case now.

Assuming I can get the tests at least running/failing for the 'right' reasons, I'll create a PR from my fork back to your own fork and/or circle back here with my findings.

**Comment by sbohlen** [comment] 2015-03-14 19:47
I've just created PR https://github.com/djechelon/spring-net/pull/1 which _does_ address the present issue, but uncovers another more tricky one that you will have to investigate resolving before proceeding.

The reason for your initial error is that Spring.Core contains a list of so-called "well-known" NamespaceParsers that are responsible for parsing config files, etc. for "expected" config namespaces.  You can see this here: https://github.com/spring-projects/spring-net/blob/master/src/Spring/Spring.Core/Objects/Factory/Xml/NamespaceParserRegistry.cs#L93-L104 and you will note that the final entry in the registration of these defines the Velocity namespace parser type as being from the `Spring.Template.Velocity` assembly.  This is, of course, _not_ the right assembly that contains the parser in your .Castle implementation and so in the simple PR I reference above I've added an app.config that registers the 'proper' namespace parser (same code/class of course, but from the `Spring.Template.Velocity.Castle` assembly in your case).

As mentioned, this resolves your current exception issue, but in the process exposes a more insidious one: if you run the tests again after accepting my PR you will find that they (nearly) all fail with a completely new exception:

```
SetUp : Spring.Objects.Factory.ObjectDefinitionStoreException : Unexpected exception parsing XML document from assembly [Spring.Template.Velocity.Castle.Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null], resource [Spring.Template.Velocity.VelocityEngineFactoryObjectTests.xml]Inner exception message= The type initializer for 'Spring.Objects.Factory.Xml.NamespaceParserRegistry' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'Spring.Objects.Factory.Xml.NamespaceParserRegistry' threw an exception.
  ----> System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for spring/parsers: Inheritance security rules violated while overriding member: 'Spring.Template.Velocity.Config.TemplateNamespaceParser.ParseElement(System.Xml.XmlElement, Spring.Objects.Factory.Xml.ParserContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
```

A careful reading of the exception message demonstrates that the root of the exception is actually being thrown by the .NET type initializer, not Spring.NET per se.  It took me some experimentation to determine the cause of this exception because the actual cause isn't _quite_ what's hinted at by the .NET run-time in this case.  The exception message would seem to suggest that the `Spring.Template.Velocity.Config.TemplateNamespaceParser.ParseElement(System.Xml.XmlElement, Spring.Objects.Factory.Xml.ParserContext)` method improperly declares itself as overriding a superclass member with a different accessibility modifier.

However, since you've literally linked the source files from the existing `Spring.Template.Velocity` project, there's of course no chance at all that this error message is correct (i.e., there's no way the source would be acceptable under `Spring.Template.Velocity` but somehow also _invalid_ under your new `Spring.Template.Velocity.Castle` project since its the _same source code_ in both projects).

Instead, what I believe is likely happening is that the .NET run-time is improperly confusing the `Spring.Template.Velocity.Config.TemplateNamespaceParser.ParseElement(System.Xml.XmlElement, Spring.Objects.Factory.Xml.ParserContext)` method from `Spring.Template.Velocity.Castle` with the same method in `Spring.Template.Velocity` because _both_ of these assemblies exist on disk in the same output folder that functions as the 'root' of the AppDomain while the tests are run.

The first step is probably for you to validate this assumption and get the tests to pass with one or more temporary work-arounds before we try to find a more permanent solution to permitting these things to co-exist properly long-term.

There are a few ways I can hypothesize that you might be able to validate this assumption:

1. you could change the output director(ies) of your .Castle and .Castle.Tests projects to some other location _not_ shared by the rest of the solution (e.g., _other than_ /build/***); this would (possibly) isolate the conflicting assemblies from ea. other but also might _not_ work b/c .Castle.Tests references Spring.Core.Tests and this in turn references Spring.Template.Velocity so you may end up in the same bad place with this approach

2. You could rename the target assembly for your .Castle project to match the existing `Spring.Template.Velocity` assembly name, unload the existing `Spring.Template.Velocity` project from the solution, and re-wire the existing references to the 'original' `Spring.Template.Velocity` project throughout the solution to point to your new one.  While this is more effort than 1. above, this approach has a much higher chance of success (though it would require you to modify e.g., your XML config file(s), etc. to reflect the new assembly name of `Spring.Template.Velocity` of course) 

3. Anything else you can think of that might permit you to bypass this .NET run-time type load error :)

If you can successfully pursue any of the above approaches (or another) to at least get your tests running/passing, then we can carefully consider a durable/longer-term approach to (somehow) permitting all of this to properly co-exist together at the same time.

Hope this makes sense; let me know your thoughts!

**Comment by djechelon** [comment] 2015-03-14 20:49
Your #2 solution suggests the validity of my initial #1 approach (*Switching from NVelocity to Castle Velocity*, completely).

There is one standing point (unfortunately I'll press the Comment button before research, violating the **Think before you post** principle). The error message talks about **security accessibility**, which is different from **method accessibility** (public, private...)

Take a look at https://stackoverflow.com/questions/3055792/inheritance-security-rules-violated-while-overriding-member-securityruleset-le, probably the AssemblyInfo isn't the same. I'll violate the above principle, check the code and come back soon

**Comment by sbohlen** [comment] 2015-03-14 20:56
lol -- good point; I guess I'd not even considered that poss. since the rest of the AssemblyInfo files have long-since been matched/sync-ed in re: security attribs.  As a 'new' project, I suppose I should have realized that this might not be a valid assumption in this case :)

Let me know what you find!

**Comment by djechelon** [comment] 2015-03-14 20:57
HAHAHAHAHA please accept my humour and imagine me singing loud the **FINAL FANTASY FANFARE**. Potential culprit found thanks to VS syntax higlight.

Let's go by order. The `AssemblyInfo.cs` contains the following:
  

    #if !NET_4_0
    [assembly: AllowPartiallyTrustedCallers]

    [assembly: SecurityCritical]

    #endif

![Screenshot](https://cloud.githubusercontent.com/assets/3042285/6653474/8f16a75e-ca94-11e4-8f29-065e32e311da.JPG)

Now what happens if I create a project without the very same configuration, including compile-time constants? Simply what compiled for one project isn't for the other. I'll check the .csproj files to make sure they define the same symbols. I should have cloned the .Casle .csproj from the old, change GUID to something new and search&replace every .Template-related if not files

Coming back soon

**Comment by djechelon** [comment] 2015-03-14 21:22
Ok I have made it. In exchange I have created https://github.com/sbohlen/spring-net/pull/1 for you to check. All template-related tests look like having passed. There were issues with the copy property of some project files, so I have checked each entry one by one in Test project to obtain the exact situation between the projects. Although I haven't done the same for the Tests project, I did a large rewrite of main project's .csproj file to match everything from the base Castle project.

I could test the DLL in my project but as my project is currently in an embrional phase I expect flawless operation for the single templated email I currently send.

That's all for tonight

**Comment by sbohlen** [comment] 2015-03-15 14:12
Tested myself and uncovered what seems to be one (last!) issue; comments here: https://github.com/sbohlen/spring-net/pull/1#issuecomment-81020772

**Comment by djechelon** [comment] 2015-03-15 17:58
https://github.com/sbohlen/spring-net/pull/2 created. Trivial fix but involved a change in the main project (+1 file forked from the `Link Source`)

**Comment by djechelon** [comment] 2015-03-21 11:30
Hi, I think there is still something left.
I tried to integrate the DLL of `Spring.Template.Velocity.Castle` but got an exception loading the `Spring.Template.Velocity` assembly. Obviously it's because the `xmlns:nv` namespace triggers something in the `Spring.Template.Velocity` assembly. A quick search showed this:

 https://github.com/spring-projects/spring-net/blob/master/src/Spring/Spring.Core/Objects/Factory/Xml/NamespaceParserRegistry.cs#L104

`wellknownNamespaceParserTypeNames["http://www.springframework.net/nvelocity"] = "Spring.Template.Velocity.Config.TemplateNamespaceParser, Spring.Template.Velocity";`

This suggests me to either fork the namespaces (bad idea), e.g. defining a new `xmlns:cv="http://www.springframework.net/castlevelocity"` in both the `NamespaceParserRegistry.cs` files and the context XML file, **or** to migrate `Spring.Core` to the new `Velocity.Castle` assembly, but that **will** force everyone using the old `Spring.Template.Velocity` to migrate to Velocity.Castle, thus creating a breaking change.

Any advice?


The following is a list of a solution-wide full-search for `Spring.Template.Velocity` string, revealing that the only reference out of the Template projects (and their tests) is within the Core assembly


    .\spring-net\src\Spring\Spring.Core\Objects\Factory\Xml\NamespaceParserRegistry.cs(104):            wellknownNamespaceParserTypeNames["http://www.springframework.net/nvelocity"] = "Spring.Template.Velocity.Config.TemplateNamespaceParser, Spring.Template.Velocity";
    .\spring-net\src\Spring\Spring.Template.Velocity\AssemblyInfo.cs(26):[assembly: AssemblyTitle("Spring.Template.Velocity")]
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\CommonsLoggingLogSystem.cs(29):namespace Spring.Template.Velocity
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\Config\TemplateNamespaceParser.cs(39):namespace Spring.Template.Velocity.Config {
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\Config\TemplateNamespaceParser.cs(51):            SchemaLocation = "/Spring.Template.Velocity.Config/spring-nvelocity-1.3.xsd")
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\Config\TemplateNamespaceParser.cs(470):        public const string SpringResourceLoaderClass = "Spring.Template.Velocity.SpringResourceLoader; Spring.Template.Velocity";
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\SpringResourceLoader.cs(29):namespace Spring.Template.Velocity {
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\VelocityConstants.cs(1):namespace Spring.Template.Velocity{
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\VelocityEngineFactory.cs(35):namespace Spring.Template.Velocity {
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\VelocityEngineFactoryObject.cs(26):namespace Spring.Template.Velocity
    .\spring-net\src\Spring\Spring.Template.Velocity\Template\Velocity\VelocityEngineUtils.cs(29):namespace Spring.Template.Velocity{
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\Config\TemplateNamespaceParserTests.cs(33):using Spring.Template.Velocity.Config;
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\Config\TemplateNamespaceParserTests.cs(37):namespace Spring.Template.Velocity.Config {
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\Config\TemplateNamespaceParserTests.cs(88):            Assert.AreEqual("Spring.Template.Velocity.Castle.Tests", getSingleProperty(velocityEngine,
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\Config\TemplateNamespaceParserTests.cs(93):            AssertMergedValue(velocityEngine, "Spring.Template.Velocity.SimpleTemplate.vm");
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\Config\TemplateNamespaceParserTests.cs(158):            Assert.AreEqual("Spring.Template.Velocity.Config.TestCustomResourceLoader; Spring.Template.Velocity.Castle.Tests",
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\config.properties(3):assembly.resource.loader.assembly=Spring.Template.Velocity.Tests
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.cs(32):namespace Spring.Template.Velocity {
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.cs(48):            AssertMergedValue(velocityEngine, "Spring.Template.Velocity.SimpleTemplate.vm");
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.cs(111):            AssertMergedValue(velocityEngine, "Spring.Template.Velocity.SimpleTemplate.vm");
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(13):            <nv:assembly name="Spring.Template.Velocity.Tests" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(20):            <nv:spring uri="assembly://Spring.Template.Velocity.Tests/Spring.Template.Velocity/"/>
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(37):                       type="Spring.Template.Velocity.Config.TestCustomResourceLoader, Spring.Template.Velocity.Tests"
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(43):    <object id="assemblyBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity">
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(48):                <entry key="assembly.resource.loader.assembly" value="Spring.Template.Velocity.Tests"/>
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(54):    <object id="fileBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(57):    <object id="pathBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(70):    <object id="springFallbackVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(71):        <property name="ResourceLoaderPath " value="assembly://Spring.Template.Velocity.Tests/Spring.Template.Velocity/" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(76):    <object id="propertiesFileBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(81):    <object id="springResourceLoaderBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\Template\Velocity\VelocityEngineTestBase.cs(32):namespace Spring.Template.Velocity {
    .\spring-net\test\Spring\Spring.Template.Velocity.Tests\VelocityCompilerOptionsTests.cs(25):using Spring.Template.Velocity;
    .\spring-net\src\Spring\Spring.Template.Velocity.Castle\AssemblyInfo.cs(26):[assembly: AssemblyTitle("Spring.Template.Velocity.Castle")]
    .\spring-net\src\Spring\Spring.Template.Velocity.Castle\Template\Velocity\Config\TemplateNamespaceParser.cs(39):namespace Spring.Template.Velocity.Config {
    .\spring-net\src\Spring\Spring.Template.Velocity.Castle\Template\Velocity\Config\TemplateNamespaceParser.cs(51):            SchemaLocation = "/Spring.Template.Velocity.Config/spring-nvelocity-1.3.xsd")
    .\spring-net\src\Spring\Spring.Template.Velocity.Castle\Template\Velocity\Config\TemplateNamespaceParser.cs(470):        public const string SpringResourceLoaderClass = "Spring.Template.Velocity.SpringResourceLoader; Spring.Template.Velocity.Castle";
    .\spring-net\src\Spring\Spring.Template.Velocity.Castle\Template\Velocity\SpringResourceLoader.cs(29):namespace Spring.Template.Velocity
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\App.config(12):      <parser type="Spring.Template.Velocity.Config.TemplateNamespaceParser, Spring.Template.Velocity.Castle" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\config.properties(3):assembly.resource.loader.assembly=Spring.Template.Velocity.Castle.Tests
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(13):            <nv:assembly name="Spring.Template.Velocity.Castle.Tests" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(20):            <nv:spring uri="assembly://Spring.Template.Velocity.Castle.Tests/Spring.Template.Velocity/"/>
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(37):                       type="Spring.Template.Velocity.Config.TestCustomResourceLoader, Spring.Template.Velocity.Castle.Tests"
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(43):    <object id="assemblyBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle">
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(48):                <entry key="assembly.resource.loader.assembly" value="Spring.Template.Velocity.Castle.Tests"/>
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(54):    <object id="fileBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(57):    <object id="pathBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(70):    <object id="springFallbackVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(71):        <property name="ResourceLoaderPath " value="assembly://Spring.Template.Velocity.Castle.Tests/Spring.Template.Velocity/" />
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(76):    <object id="propertiesFileBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle" >
    .\spring-net\test\Spring\Spring.Template.Velocity.Castle.Tests\Template\Velocity\VelocityEngineFactoryObjectTests.xml(81):    <object id="springResourceLoaderBasedVelocityEngine" type="Spring.Template.Velocity.VelocityEngineFactoryObject, Spring.Template.Velocity.Castle" >


I don't think it's a good idea to sumbit my PR today because if this issue that currently prevents me from integrating the assembly into my Spring-based webapp. Of course if there is a trick to override the parser definition (e.g. calling `public static void RegisterParser(Type parserType, string namespaceUri, string schemaLocation)` at the right point) I'll be willing to try that.

Thank you for your help.

**Comment by sbohlen** [comment] 2015-03-21 14:41
I concur that we don't want to define a 'replacement' additional namespace.

You're entirely correct that the 'well-known' parser attempting to be registered by `Spring.Core` is hard-coded to look in the `Spring.Template.Velocity` assembly, and so this will indeed fail (since you're parser is in a different assembly).

As I hinted at in my commit message here https://github.com/sbohlen/spring-net/commit/72c2f580c192a69d69c9b67f0fc8e1b1b0157338, you have to register the _actual_ location of the parser with the AppContext in order for it to find it properly.  Are you 100% certain that in your actual project you're properly registering the NamespaceParser from the `.Castle` assembly the way I did for your test project here: https://github.com/sbohlen/spring-net/blob/master/test/Spring/Spring.Template.Velocity.Castle.Tests/App.config ?

You need to do this to overwrite the 'well-known' parser registered by default for the _nvelocity_ namespace with the one you actually want to use.  Once you do this your app should properly use the correct parser and no longer attempt to load the one from the `Spring.Template.Velocity` assembly (which, as you point out, isn't there and will cause an the error you are experiencing).

Can you ensure that you've followed that step and let me know if you're _still_ getting an error?

**Comment by djechelon** [comment] 2015-03-21 14:56
Ok, I didn't fully understand the role of the spring-parsers tag. Anyway I still tried to run `RegisterParser` by code and it... ahem... might work just fine too as expected! I mean, since I have the official Spring Core from NuGet in my project plus the self-compiled Velocity Castle integration project, the second is bound to a version of Spring Core compiled without the `PublicKey` and instantiating the `TemplateNamespaceParser` triggers a reflection exception because .NET can't rightfully find the Spring.Core assembly without strong name.

I mean that the entire thing works as soon as it is compiled with the official SNK from Spring team, even if not yet released via NuGet. Or if all the Spring distribution into the project is self-compiled with any, or none, SNK.

In order to do a "test drive" of Velocity Castle I'd have to bring into my project all Spring dlls compiled by me. I can do this, but as the code looks promising I think the time for a PR has come, so other people can start integrating too if they wish.

**Comment by sbohlen** [comment] 2015-03-21 15:13
OK, great -- I agree with your estimation that its _likley_ to work.  We're planning on baking the final 2.0.0-GA release bits this weekend and since this wasn't manifest in the 2.0.0-RC2 packages (and we're still not 100% certain it will work as intended) I'm probably going to _exclude_ this work from the 2.0.0-GA bits as being too nascent to release formally just yet.

After we push 2.0.0-GA, I'll accept the PR and push pre-release 2.1.0-alpha1 NuGet packages that contain this so that people can easily use NuGet to consume the bits for testing/evaluation of your Castle Velocity integration.

Make sense --?

**Comment by djechelon** [comment] 2015-03-21 15:32
Makes lots of sense, I was really waiting for a GA version of Spring (anyways) and I agree this work **must** be first released as unstable, hopefully via NuGet

**Comment by lahma** [comment] 2022-10-15 17:07
I'm doing a rude experiment with closing this, like what stale bot does, but maybe more human as I will probably actually react to feedback. As this issue has been stale for so long, I'll close it. If it's still an issue you would like to pursue, we can definitely reopen. 

With limited resources this is just something that we need to do. Thank you for your understanding.

**Closed by lahma** 2022-10-15 17:07 UTC
Labels: Enhancement
